namespace OllamaRoleplay.Models;

public static class Languages
{
    public static Dictionary<string, Dictionary<string, string>> Translations { get; } = new()
    {
        ["fr"] = new Dictionary<string, string>
        {
            ["AppTitle"] = "🤖 Ollama Roleplay - Chat IA Local",
            ["StatusOllama"] = "Status Ollama",
            ["CheckConnection"] = "🔄 Vérifier connexion",
            ["LLMModel"] = "Modèle LLM",
            ["Size"] = "Taille",
            ["InternetAccess"] = "Accès Internet",
            ["Enabled"] = "Activé",
            ["Disabled"] = "Désactivé (mode hors-ligne)",
            ["InternetNote"] = "Désactivé = Le LLM ne peut pas chercher sur internet",
            ["Characters"] = "Personnages",
            ["NewCharacter"] = "Nouveau personnage",
            ["Delete"] = "Supprimer",
            ["EditCharacter"] = "✏️ Éditer le personnage",
            ["Name"] = "Nom",
            ["Age"] = "Âge",
            ["Gender"] = "Sexe",
            ["Male"] = "Masculin",
            ["Female"] = "Féminin",
            ["Language"] = "Langue",
            ["Description"] = "Description physique",
            ["Likes"] = "Ce qu'il/elle aime",
            ["Dislikes"] = "Ce qu'il/elle déteste",
            ["Personality"] = "Personnalité",
            ["VoiceSample"] = "Échantillon vocal (MP3)",
            ["SelectVoice"] = "Sélectionner...",
            ["Save"] = "💾 Sauvegarder",
            ["NoCharacter"] = "Aucun personnage",
            ["Clear"] = "🗑️ Effacer",
            ["SaveChat"] = "💾 Sauvegarder",
            ["Send"] = "📤 Envoyer",
            ["Stop"] = "⏹️ Stop",
            ["TypeMessage"] = "Écrivez votre message...",
            ["Ready"] = "Prêt",
            ["Connected"] = "Connecté à Ollama",
            ["NotConnected"] = "Ollama non disponible - Lancez 'ollama serve'",
            ["Checking"] = "Vérification de la connexion à Ollama...",
            ["ModelsAvailable"] = "modèle(s) disponible(s)",
            ["NoModels"] = "Aucun modèle trouvé - Exécutez 'ollama pull llama3.2'",
            ["Generating"] = "Génération en cours...",
            ["Generated"] = "Réponse générée",
            ["Cancelled"] = "Génération annulée",
            ["Error"] = "Erreur",
            ["ErrorWriteMessage"] = "Erreur: Écrivez un message",
            ["ErrorSelectCharacter"] = "Erreur: Sélectionnez un personnage",
            ["ErrorSelectModel"] = "Erreur: Sélectionnez un modèle LLM",
            ["CharacterSaved"] = "Personnage sauvegardé",
            ["ChatCleared"] = "Conversation effacée",
            ["ChatSaved"] = "Conversation sauvegardée",
            ["ConfirmDelete"] = "Supprimer ce personnage ?",
            ["Confirmation"] = "Confirmation",
            ["You"] = "Vous",
            ["Character"] = "Personnage",
            ["Settings"] = "⚙️ Paramètres",
            ["AppLanguage"] = "Langue de l'application",
            ["Copy"] = "Copier",
            ["Edit"] = "Modifier",
            ["DeleteMessage"] = "Supprimer",
            ["EditMessage"] = "Modifier le message",
            ["Stats"] = "⏱️ {0}s | 📊 {1} tokens | ⚡ {2} t/s",
            ["PlayVoice"] = "🔊 Lire",
            ["StopVoice"] = "⏹️ Arrêter"
        },
        ["en"] = new Dictionary<string, string>
        {
            ["AppTitle"] = "🤖 Ollama Roleplay - Local AI Chat",
            ["StatusOllama"] = "Ollama Status",
            ["CheckConnection"] = "🔄 Check connection",
            ["LLMModel"] = "LLM Model",
            ["Size"] = "Size",
            ["InternetAccess"] = "Internet Access",
            ["Enabled"] = "Enabled",
            ["Disabled"] = "Disabled (offline mode)",
            ["InternetNote"] = "Disabled = LLM cannot search the internet",
            ["Characters"] = "Characters",
            ["NewCharacter"] = "New character",
            ["Delete"] = "Delete",
            ["EditCharacter"] = "✏️ Edit character",
            ["Name"] = "Name",
            ["Age"] = "Age",
            ["Gender"] = "Gender",
            ["Male"] = "Male",
            ["Female"] = "Female",
            ["Language"] = "Language",
            ["Description"] = "Physical description",
            ["Likes"] = "Likes/Interests",
            ["Dislikes"] = "Dislikes/Fears",
            ["Personality"] = "Personality",
            ["VoiceSample"] = "Voice sample (MP3)",
            ["SelectVoice"] = "Select...",
            ["Save"] = "💾 Save",
            ["NoCharacter"] = "No character",
            ["Clear"] = "🗑️ Clear",
            ["SaveChat"] = "💾 Save",
            ["Send"] = "📤 Send",
            ["Stop"] = "⏹️ Stop",
            ["TypeMessage"] = "Type your message...",
            ["Ready"] = "Ready",
            ["Connected"] = "Connected to Ollama",
            ["NotConnected"] = "Ollama not available - Run 'ollama serve'",
            ["Checking"] = "Checking connection to Ollama...",
            ["ModelsAvailable"] = "model(s) available",
            ["NoModels"] = "No models found - Run 'ollama pull llama3.2'",
            ["Generating"] = "Generating...",
            ["Generated"] = "Response generated",
            ["Cancelled"] = "Generation cancelled",
            ["Error"] = "Error",
            ["ErrorWriteMessage"] = "Error: Write a message",
            ["ErrorSelectCharacter"] = "Error: Select a character",
            ["ErrorSelectModel"] = "Error: Select a LLM model",
            ["CharacterSaved"] = "Character saved",
            ["ChatCleared"] = "Chat cleared",
            ["ChatSaved"] = "Chat saved",
            ["ConfirmDelete"] = "Delete this character?",
            ["Confirmation"] = "Confirmation",
            ["You"] = "You",
            ["Character"] = "Character",
            ["Settings"] = "⚙️ Settings",
            ["AppLanguage"] = "Application Language",
            ["Copy"] = "Copy",
            ["Edit"] = "Edit",
            ["DeleteMessage"] = "Delete",
            ["EditMessage"] = "Edit message",
            ["Stats"] = "⏱️ {0}s | 📊 {1} tokens | ⚡ {2} t/s",
            ["PlayVoice"] = "🔊 Play",
            ["StopVoice"] = "⏹️ Stop"
        }
    };

    public static string Get(string key, string lang = "fr")
    {
        if (Translations.TryGetValue(lang, out var dict) && dict.TryGetValue(key, out var value))
            return value;
        if (Translations["en"].TryGetValue(key, out var fallback))
            return fallback;
        return key;
    }
}
